frontend: 
  url: /auth/
  port: 8080
checker: 
  port: 8081
targets:
  SomeOauth:
    name: External Name
    icon: github
    type: github
    baseurl: https://github.example.com
    clientid: 34124earo3149141951
    clienttoken: asr234513-051-3tfjekr130-948
